#!/bin/bash

if [ $1 == "makemigrations" ]
then
    shift
    msg="$@"
    exec alembic revision --autogenerate -m "$msg"
elif [ $1 == "run" ]
then
    exec ./scripts/start-reload.sh
elif [ $1 == "migrate" ]
then
    exec alembic upgrade head
elif [ $1 == "shell" ]
then
    exec ipython
elif [ $1 == "test" ]
then
    shift
    msg="$@"
    exec pytest app/tests/"${@}"
elif [ $1 == "tests" ]
then
    shift
    msg="$@"
    exec ./scripts/test.sh
elif [ $1 == "tests-cov" ]
then
    shift
    msg="$@"
    exec ./scripts/test.sh --cov-report=html "${@}"
else
    exec $@
fi
